version = 1

exclude_patterns = [
    "data/**",
    "templates/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"
enabled = true

[[transformers]]
name = "black"
enabled = true